# Custom Language File for Launcher Customizer

[ejs.app]
title = "DreamClient Launcher - Beta"

[ejs.landing]
mediaGitHubURL = "https://launcher.imperomc.eu"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.imperomc.eu"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "BENVENUTO/A SU DreamClient"
welcomeDescription = "Sei a pochi passi da DreamClient"
welcomeDescCTA = "Copyright © 2025 - DreamClient"
